### ISSUE TITLE
Team Selector - Limit opponent affinities for Fire incorrect

### ISSUE THREAD

**Issue by Marauder69** [giero/LGoH-deck-suggester#1]
Limit opponent affinities for Fire incorrect

I selected FIRE and seem to be presented with a team for DARK. All Light based cards, confirmed by selecting DARK and got the same team

Keep up the good work

**Comment by giero** [comment]
Hey,

This doesn't have to be a bug - maybe your Light cards are much stronger than your Water cards.
Could you export your cards and paste whole string here or - event better - by [pastebin](https://pastebin.com/)?

Thanks :)

**Comment by Marauder69** [comment]
I wouldn’t expect all yellow… but willing to be corrected.

 

Mark

**Comment by giero** [comment]
Yeap, as I suspected.

Your "Catherine, Fairy Queen" has "300% Damage and HP for all Light Warrior Heroes" and you have some strong Light Warrior cards. Remember that leader's bonus is quite important.

Within your Water cards only "Butcher, The Cursed" has strong leader skill which applies for more than 1 card (2 exactly) ... so Light deck is much powerful than any deck combined from your Water cards.

**Comment by Marauder69** [comment]
WOW

 

I would never have thought, not entered into battle without Blue

Will have to give that a go, thanks again my friend :)
