### ISSUE TITLE
Adding Michtlantecuhtli

### ISSUE THREAD

**Issue by aerinvdz** [giero/LGoH-deck-suggester#11]
I added stats for new hero for 3*, 4* and 5*, but the spreadsheet is not updating the hero list on the deck suggester.  I did click the link to update, and it said the update was complete, but the new hero was not added.

Also, this hero has a counterskill of "Dispel Chaos" which is not available on the list.

**Comment by giero** [comment]
Thx for info - I'll check it out asap

**Comment by aerinvdz** [comment]
Thanks!  If it's something I need to enter differently, please let me know.  I should have 6* information soon.


Melissa

**Comment by giero** [comment]
I added missing "Dispel Chaos" so Michtlantecuhtli is on the list now :)

**Comment by stripe1000** [comment]
Dispel Chaos is working well on the spreadsheet but still not updating into the GUI.

Edit: please ignore comment.  The issue was on my end with my browser not refreshing the page properly and taking it from the cache instead.

**Comment by aerinvdz** [comment]
I had an error earlier that it won't import the record because it doesn't like the description of the battle skill (I added a comment to the spreadsheet).  As far as I can tell, it is formatted the same as the field above.  It's for 5* Ozomatli.


Melissa
