### ISSUE TITLE
Oasis of Ruin

### ISSUE THREAD

**Issue by patnodewf** [giero/LGoH-deck-suggester#14]
Adding heroes with the Mystic race returns an error saying that Mystic is an invalid race

**Comment by patnodewf** [comment]
And now it says:

`... and it's failed for [earth] Ophra the Conjurer ***

Invalid leader ability format "Earth Mystic Might I: 175% Damage and HP for all Earth Mystic Heroes."`

**Comment by patnodewf** [comment]
oh, the error changed because someone else completed removed all the Haroun versions I added in there, and changed Ophra's race from Mystic to Ancient - which is not accurate.

**Comment by giero** [comment]
> Invalid leader ability format "Earth Mystic Might I: 175% Damage and HP for all Earth Mystic Heroes."

It's because you put a dot at the end of this skill

_Mystic_ race must be the new one - I added it to the app :)

And also I restored your version of the spreadsheet - Haroun is back :)

EDIT: heroes list is up to date now

**Comment by patnodewf** [comment]
Thank you!
