### ISSUE TITLE
suggested decks ot loading past 67%

### ISSUE THREAD

**Issue by squiremanduxv** [giero/LGoH-deck-suggester#4]

**Comment by giero** [comment]
Sorry, but I have no idea what do you mean.

**Comment by squiremanduxv** [comment]
On the suggested decks tab and press calculate decks, it loads only to 67%. I have deleted my cookies and all with no luck of it going past 67%. I don't know of any other way to explain it. I have all my cards added and updated the card file also.

**Comment by squiremanduxv** [comment]
[file.pdf](https://github.com/giero/LGoH-deck-suggester/files/1626797/file.pdf)
maybe this will help a little

**Comment by giero** [comment]
I won't open it ;)

Could you export your team and paste it here?

**Comment by giero** [comment]
Nevermind - i figured it out what makes this issue :) It's Flameheart - he has new type of leader ability (GvG only).

Already fixed :)

**Comment by squiremanduxv** [comment]
Thank you for fixing it
