### ISSUE TITLE
Missing Hero: Nydorn the Black

### ISSUE THREAD

**Issue by Chrono9084** [giero/LGoH-deck-suggester#9]
Love this tool but noticed it was missing one of my heroes: Nydorn the Black.  Just and FYI.

**Comment by giero** [comment]
Hey,

I am no longer playing this game anymore, so it depends on players, to keep character base up to date :) You can add missing heroes here: https://goo.gl/e2ql9O

Adding missing heroes is pretty strightforward. Just look at other positions and add your heroes the same way as the others (best source of data is in your in-game CODEX).

After that (and after few minutes - spreadsheet need some time to update) go to my app, then "List of heroes" tab and press "Update now". And that's it :)
